### ISSUE TITLE
Compare support

### ISSUE THREAD

**Issue by lucat1** [kanidm/ldap3#17]
I see it is explicitly listed as not implemented in the readme but I'm curious as to what is the sentiment towards the `compare` ldap feature. Is is just not implemented because of a lack of time or has it been explicitly left out for some other reason?

I'm using LLDAP which is based on this library and any Django service apparently uses this LDAP call during sing-on, so a wide range of web applications supporting LDAP authentication are being left unsupported this way.

**Comment by Firstyear** [comment]
Oh it just hasn't been added yet. There are two parts to it though. First is this library just needs to add the compare operation from rfc4511, then lldap will need to actually add support to act on that operation. @nitnelave is this something you'd be interested to add to lldap if we added the compare op to this library?

**Comment by nitnelave** [comment]
Yes, I directed him your way :)
If you add support for compare, I'll handle it in LLDAP.
