### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by kolapapa** [kanidm/ldap3#20]
Hello kanidm, thank you very much for your repository, which helped me a lot, but I have a question, is there any plan to upgrade `lber` to version `0.4.0`? Because I received a warning like this when compiling: `warning: the following packages contain code that will be rejected by a future version of Rust: nom v2.2.1`.

**Comment by Firstyear** [comment]
I didn't know that warning was occuring! I'll update it soon then :)

**Comment by Firstyear** [comment]
Thanks @kolapapa I have released this :) thanks for reporting.
