### ISSUE TITLE
Wild Card Subsctring filter is not supported

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [kanidm/ldap3#39]
``` rs
 let filter = parse_ldap_filter_str("(cn=*Info*)").unwrap();
```
this will throw an error, however, it is specified in [rfc4515](https://datatracker.ietf.org/doc/html/rfc4515#section-4)

**Comment by Firstyear** [comment]
@irvingoujAtDevolution Was this fixed by your latest PR?

**Comment by irvingoujAtDevolution** [comment]
@Firstyear yes it is
