### ISSUE TITLE
An error occurred writing to the transport

### ISSUE THREAD

**Issue by kolapapa** [kanidm/ldap3#53]
I recently encountered an issue while using `ldap_client`:
After storing two `LdapClient` instances, I automatically select which `LdapClient` to use for processing based on the content of the search request. However, I often encounter the error `"An error occurred writing to the transport"`. This error seems to indicate that the TCP stream has been disconnected.  I would like to know how to optimize this issue.

**Comment by Firstyear** [comment]
Sorry I didn't respond in time. Did you resolve this?

**Comment by kolapapa** [comment]
> Sorry I didn't respond in time. Did you resolve this?

Yes, I realize it's my fault. 🥲

**Comment by Firstyear** [comment]
No problem at all, glad you solved it. Was there anything this library could have done to make it easier to find the fault?
