### ISSUE TITLE
`ServerOps::try_from` should return a meaningful error

### ISSUE THREAD

**Issue by fooker** [kanidm/ldap3#9]
`ServerOps::try_from` is defined to return `()` on error. This could be improved to reflect what went wrong in the conversion.

**Comment by Firstyear** [comment]
Yep, this has been needed for a while. Initially it was just about getting it to work, but you're right the error message should be better.

**Comment by Firstyear** [comment]
A big chunk of this was done today in #31, sorry it took so long - I have been very distracted and busy.

**Comment by Firstyear** [comment]
Sorry for the delay, this was fixed a few months ago.
